name: Build and Deploy CRM User Management Service

on:
  push:
    branches: [ release, main ]

permissions:
  id-token: write
  contents: read

env:
  FUNCTION: ${{ vars.AWS_LAMBDA_FUNCTION_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Build
        run: ./gradlew buildZip
        
      - name: Save artifact
        uses: actions/upload-artifact@v5
        with:
          name: app.jar
          path: ./build/distributions/
          compression-level: 0
          if-no-files-found: error

  push:
    runs-on: ubuntu-latest
    environment: Production
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ needs.build.outputs.artifact-id }}
          path: out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Upload artifact to S3
        run: aws s3 sync out/ s3://amazobank-lambdas/

      - name: Deploy Lambda Function from S3
        run: >
          aws lambda update-function-code
          --function-name $FUNCTION
          --s3-bucket amazobank-lambdas
          --s3-key project-2025-26T1-g2-t2-crm-user-management-1.0.0.zip
